package com.bookstore.onlinebookstore.dto;

import lombok.Getter;
import lombok.Setter;

/**
 * This is a Data Transfer Object (DTO).
 * Unlike an Entity, it is NOT saved in the database. It is a "container" used
 * to carry data from the Frontend to the Backend during the checkout process.
 */
@Getter
@Setter
public class CheckoutItem {

    // The ID of the book the customer wants to buy
    private Long bookId;

    // The name of the book for confirmation display
    private String title;

    // The unit price of the book
    private double price;

    // The number of copies the customer is purchasing
    private int quantity;

    // Standard Getters and Setters are generated by Lombok
    // to keep the data accessible to the OrderService.
}